variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

image: "rust:1.37.0"

.cargo_cache: &cargo_cache
  cache:
    paths:
      - .cargo

stages:
  - validate
  - build
  - release
  - package

test:
  <<: *cargo_cache
  stage: validate
  script:
    - cargo test  --verbose

format:
  <<: *cargo_cache
  stage: validate
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all --verbose -- --check

lint:
  <<: *cargo_cache
  stage: validate
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --verbose -- -D warnings

build:
  <<: *cargo_cache
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

release:
  <<: *cargo_cache
  stage: release
  script:
    - cargo build --release --target x86_64-apple-darwin
  only:
    - tags

package:
  stage: package
  script:
    - cd target/x86_64-apple-darwin/release
    - tar -czf protovend.tar.gz protovend
    - shasum -a 256 protovend.tar.gz > sha256.txt
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file protovend.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/protovend/${CI_COMMIT_TAG}/protovend.tar.gz"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file sha256.txt "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/protovend/${CI_COMMIT_TAG}/sha256.txt"'
  only:
    - tags
